# Generated by Django 3.0b1 on 2019-12-16 10:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=50)),
                ('text_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('page_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_page_number', models.IntegerField()),
                ('manuscript_page_number', models.IntegerField()),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manuscript')),
                ('same_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800)),
                ('label', models.CharField(max_length=50)),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hypo_text', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Chapter')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Page')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatedLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800)),
                ('label', models.CharField(max_length=50)),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hypo_text', django.contrib.postgres.fields.jsonb.JSONField()),
                ('complete', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
                ('next_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='next', to='api.AnnotatedLine')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
                ('previous_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='api.AnnotatedLine')),
                ('same_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AnnotatedLine')),
            ],
        ),
    ]
