# Generated by Django 3.0b1 on 2020-02-19 14:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=800)),
                ('label', models.CharField(default='', max_length=50)),
                ('research_note', models.CharField(default='', max_length=800)),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('complete', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(upload_to='manuscript_images/')),
                ('currently_marking', models.IntegerField(default=0)),
                ('currently_annotating', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=50)),
                ('text_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('page_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Annotation')),
                ('same_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corresponding', to='api.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Annotation')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Manuscript'),
        ),
        migrations.CreateModel(
            name='AnnotatedLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypo_text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Annotation')),
                ('next_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='api.AnnotatedLine')),
                ('previous_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='api.AnnotatedLine')),
                ('text_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.TextField')),
            ],
        ),
    ]
