# Generated by Django 3.0b1 on 2019-12-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=50)),
                ('text_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('page_direction', models.CharField(choices=[('ltr', 'Left-to-right'), ('rtl', 'Right-to-left')], default='rtl', max_length=3)),
                ('filepath', models.FileField(upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('aside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Aside')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounding_box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Rectangle')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manuscript')),
                ('same_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='aside',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Chapter'),
        ),
        migrations.AddField(
            model_name='aside',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Page'),
        ),
        migrations.CreateModel(
            name='AnnotatedLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=800)),
                ('label', models.CharField(max_length=50)),
                ('bounding_box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Rectangle')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
                ('next_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='next', to='api.AnnotatedLine')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
                ('previous_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='api.AnnotatedLine')),
            ],
        ),
    ]
