# Generated by Django 3.0b1 on 2020-03-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedline',
            name='text_field',
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_line', to='api.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='api.Manuscript'),
        ),
        migrations.AlterField(
            model_name='aside',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aside', to='api.Annotation'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='api.Annotation'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='currently_annotating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='currently_marking',
            field=models.IntegerField(default=1),
        ),
    ]
