# Generated by Django 3.0b1 on 2019-12-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aside',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
