# Generated by Django 3.0b1 on 2020-03-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200309_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Annotation'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Annotation'),
        ),
    ]
