# Generated by Django 3.0b1 on 2020-02-03 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200129_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='page',
            name='manuscript_page_number',
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounding_box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
            ],
        ),
    ]
