# Generated by Django 3.0b1 on 2020-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200309_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotator',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
