# Generated by Django 3.0b1 on 2020-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200203_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
