# Generated by Django 3.0b1 on 2020-02-06 13:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_manuscript_current_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedline',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='annotatedline',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aside',
            name='chapter',
        ),
        migrations.AddField(
            model_name='annotatedline',
            name='text_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TextField'),
        ),
        migrations.AddField(
            model_name='aside',
            name='text_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TextField'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Chapter'),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='hypo_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='next_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='api.AnnotatedLine'),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='previous_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='api.AnnotatedLine'),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='same_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corresponding', to='api.AnnotatedLine'),
        ),
        migrations.AlterField(
            model_name='annotatedline',
            name='text',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='aside',
            name='hypo_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aside',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aside',
            name='text',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='same_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corresponding', to='api.Chapter'),
        ),
    ]
